version: '3.8'

services:
  app:
    build:
      context: $PWD
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    environment:
      - NAME=Calendar_app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/src/auth/Gmail/client_secretfile.json
      - PYTHONPATH=/app
    volumes:
      - $PWD:/app
      - $PWD/logs:app/logs
    command: python -m src.main

  tests:
    build:
      context: $PWD
      dockerfile: docker/Dockerfile
    volumes:
      - $PWD:/app
      - $PWD/logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: python -m unittest discover -s tests -p "*.py"
